name: Playwright Java Maven ExtentReports CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '24'

    - name: Verify Maven is installed
      run: mvn --version

    - name: Install Playwright Browsers
      run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"
      working-directory: apps
      continue-on-error: true

    - name: Run Tests
      run: mvn clean test
      working-directory: apps

    - name: Upload ExtentReports
      if: always() # Upload even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: extent-report
        path: reports/index.html # Adjust to your actual report path
