name: Playwright Java Maven ExtentReports CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 24
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '24'

    - name: Install Playwright Browsers
      run: mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install"
      working-directory: apps

    - name: Run TestNG suite
      run: mvn clean test -DsuiteXmlFile=testng.xml
      working-directory: apps

    - name: Upload ExtentReports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: extent-report
        path: apps/reports/

    - name: Upload Surefire Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: apps/target/surefire-reports/
